// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJj38j_YTC5IjdTFIrsdBY8ZPCKt5jd8',
    appId: '1:328097407117:android:77a46c5fcfe71c7409c2c4',
    messagingSenderId: '328097407117',
    projectId: 'wdni-518ff',
    databaseURL: 'https://wdni-518ff-default-rtdb.firebaseio.com',
    storageBucket: 'wdni-518ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6M2CwWg_-UV-OgNawX_0Vl5U21VH23GU',
    appId: '1:328097407117:ios:7e8d5f7077671e4509c2c4',
    messagingSenderId: '328097407117',
    projectId: 'wdni-518ff',
    databaseURL: 'https://wdni-518ff-default-rtdb.firebaseio.com',
    storageBucket: 'wdni-518ff.firebasestorage.app',
    androidClientId: '328097407117-1pbo48ep4mi8sgrrj0of6gdntmeo5i3t.apps.googleusercontent.com',
    iosClientId: '328097407117-vs34u6smbhhvve562r1oihmfn1k4l1de.apps.googleusercontent.com',
    iosBundleId: 'com.app.wdniCustomers',
  );

}